DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS squawks;


CREATE TABLE event (
  event_id INTEGER PRIMARY KEY AUTOINCREMENT,
  type_of_action INT NOT NULL,
  user_id VARCHAR NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
  user_id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  is_admin BOOLEAN NOT NULL
);

CREATE TABLE squawks (
  squawk_id INTEGER PRIMARY KEY AUTOINCREMENT,
  content VARCHAR NOT NULL,
  is_reply_to INT,
  user_id INT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);